### PR TITLE
fix(ingest): normalize root parent span

### LINKED ISSUE #8: Fix OTLP ingest dropping root spans when parent_span_id is nil
## User request
Tracing should ingest and persist OTLP **root spans** (spans with no parent) so they are retrievable via `TracingService` APIs. This is currently blocking downstream E2E coverage (e.g. agents-orchestrator tracing canary exports successfully but `GetTrace` returns `NotFound`).

## Specification (research)
- In tracing **v0.2.0**:
  - DB schema (`migrations/0001_init.sql`) defines `spans.parent_span_id BYTEA NOT NULL DEFAULT ''`.
  - Ingest (`internal/ingest/ingest.go:spanToRow`) sets `ParentSpanID: span.GetParentSpanId()`.
    - For OTLP root spans, `ParentSpanId` is typically *unset* on the wire → Go decodes it as `nil`.
  - Store upsert (`internal/store/store.go:UpsertSpan`) always binds `parent_span_id`.
    - With pgx, `nil []byte` is encoded as SQL `NULL`.
    - This violates the `NOT NULL` constraint, so the insert fails and the span is dropped.
  - Ingest swallows the upsert error (logs + increments `rejectedSpans`) and returns gRPC OK (with `PartialSuccess`), so exporters/canaries can miss the failure.

### Required fix
- Normalize root spans so the stored `parent_span_id` is **empty bytea** (zero-length), not `NULL`.
  - Recommended: in `spanToRow`, if `span.GetParentSpanId() == nil`, set it to `[]byte{}` before constructing the DB row.
  - Optional hardening: also normalize in `Store.UpsertSpan` as a defensive layer.
- Add/extend tests to cover this regression:
  - A root span (no parent) should be stored successfully and retrievable via `GetTrace`.

### Release / rollout
- After merge, cut a patch release (e.g. **v0.2.1**) so bootstrap-based CI clusters can consume the fixed image+chart.

### PR DESCRIPTION
**Pull request by casey-brooks**
## Summary
- normalize nil parent span IDs to empty bytes before insert
- add ingest test covering root-span parent normalization

## Testing
- buf generate buf.build/agynio/api --path agynio/api/tracing/v1 --path agynio/api/notifications/v1
- go test ./...
- go vet ./...

Closes #8

### CODE REVIEW

**Comment by casey-brooks** [comment]
Summary:
- Normalized nil parent span IDs to empty bytes before insert so root spans are stored.
- Added ingest unit test covering root-span parent normalization.

Tests:
- buf generate buf.build/agynio/api --path agynio/api/tracing/v1 --path agynio/api/notifications/v1
- go test ./...
- go vet ./...

File: internal/ingest/ingest_test.go [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+import (
+	"testing"
+
+	"github.com/stretchr/testify/require"
+	tracev1 "go.opentelemetry.io/proto/otlp/trace/v1"
+)
+
+func TestSpanToRowNormalizesParentSpanID(t *testing.T) {
+	span := &tracev1.Span{
+		TraceId:           []byte{0x01},
```
Comment (noa-lucent) [inline internal/ingest/ingest_test.go:12]: [minor] Consider using valid OTLP ID lengths here (trace_id = 16 bytes, span_id = 8 bytes). It keeps the unit test realistic and avoids future ingest-side ID validation changes breaking this test for unrelated reasons (e.g., use make([]byte, 16)/make([]byte, 8)).

**Review by noa-lucent — APPROVED** [review]
Fix looks correct: spanToRow now normalizes nil ParentSpanId to empty bytes, avoiding NOT NULL violations on spans.parent_span_id, and a unit test covers the regression.\n\nMinor: consider using valid OTLP trace/span ID lengths in the new unit test (16/8 bytes) to keep it future-proof if ingest-side ID validation is added.
